---
title: "Trabajo Práctico 3 - Estandarización de Tasas"
author: "Gazze Simón - Moresi Manuel"
date: "2025-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción

...

## Manejo de bases de datos

```{r}
#install.packages(c("readxl", "dplyr", "stringr", "openxlsx"))
library(readr)
library(readxl)
library(dplyr)
library(stringr)
library(openxlsx)
library(dbplyr)
library(tidyr)

if(FALSE){ 

archivo <- "/Users/Simon/Downloads/Bioestad-istica/TP3/c2_proyecciones_prov_2010_2040.xls"

# Obtener nombres de todas las hojas
nombres_hojas <- excel_sheets(archivo)

nombres_hojas <- nombres_hojas[2:26]

# Crear lista para guardar los data frames de cada hoja
lista_provincias <- list()

# Loop por cada hoja
for (hoja in nombres_hojas) {
  
  # Leer solo el rango que te interesa
  datos <- read_excel(archivo, sheet = hoja, range = "A64:H84", col_names = FALSE)
  
  # Seleccionar columnas A, F, G y H
  datos <- datos %>% select(1, 6, 7, 8)
  
  # Renombrar columnas
  colnames(datos) <- c("Grupo_etario", "Ambos_sexos", "Masculino", "Femenino")
  
  # Extraer nombre de la provincia (parte después del guión)
  nombre_provincia <- str_split(hoja, "-", simplify = TRUE)[,2]
  
  cod_provincia <- as.numeric(str_split(hoja, "-", simplify = TRUE)[,1])
  
  # Agregar columna Provincia
  datos <- datos %>%
    mutate(Provincia = nombre_provincia, Codigo_prov = cod_provincia) %>%
    select(Codigo_prov, Provincia, everything())
  
  # Guardar en la lista
  lista_provincias[[hoja]] <- datos
}

# Unir todo en un solo data frame
proyeccion_total <- bind_rows(lista_provincias)

# Guardar como archivo Excel
write.xlsx(proyeccion_total, "proyeccion_poblacion_total.xlsx")

}

proyeccion_total <- read_excel("./proyeccion_poblacion_total.xlsx")

proyeccion_total <- proyeccion_total %>%
  mutate(Grupo_etario = ifelse(Grupo_etario %in% c("80-84", "85-89", "90-94", "95-99", "100 y más"), "80 y más", Grupo_etario)) %>%
  group_by(Codigo_prov,Provincia,Grupo_etario) %>%
  summarise(Ambos_sexos = sum(Ambos_sexos),
            Masculino = sum(Masculino),
            Femenino = sum(Femenino),
            .groups = "drop")
  
proyeccion_total <- proyeccion_total %>%
  mutate(Grupo_etario = factor(Grupo_etario, levels = c(
    "0-4", "5-9", "10-14", "15-19", "20-24", "25-29", 
    "30-34", "35-39", "40-44", "45-49", "50-54", 
    "55-59", "60-64", "65-69", "70-74", "75-79", "80 y más"
  )))

```

Agrego las defunciones por diabetes

```{r}
defunciones_2023 <- read_delim("./defweb23.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

def_final <- defunciones_2023 %>%
  mutate(SEXO = ifelse(SEXO == 1, "Def_masculino", "Def_femenino")) %>%
  pivot_wider(names_from = SEXO, values_from = CUENTA) %>%
  replace_na(list(Def_masculino = 0, Def_femenino = 0)) %>%
  group_by(Codigo_prov) %>%
  mutate(Def_ambos_sexos = Def_masculino + Def_femenino) %>%
  ungroup()


total_pais <- def_final %>%
  group_by(Grupo_etario) %>%
  summarise(
    Def_masculino = sum(Def_masculino, na.rm = TRUE),
    Def_femenino = sum(Def_femenino, na.rm = TRUE),
    Def_ambos_sexos = sum(Def_ambos_sexos, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(Codigo_prov = 1) %>%
  select(Codigo_prov, Grupo_etario, Def_masculino, Def_femenino, Def_ambos_sexos)


def_final <- bind_rows(def_final, total_pais)


df_unido <- proyeccion_total %>%
  left_join(def_final, by = c("Codigo_prov", "Grupo_etario")) %>%
  mutate(
    Def_masculino = replace_na(Def_masculino, 0),
    Def_femenino = replace_na(Def_femenino, 0),
    Def_ambos_sexos = replace_na(Def_ambos_sexos, 0)
  )

```

